namespace HotelReservationLibrary.DomainObjects
{

    public class Reservation
    {
        //ToDo:  Convert these to enums.  But this requires changes to client code.
        public static string SINGLE_ROOM = "Single";
        public static string DOUBLE_ROOM = "Double";
        public static string SUITE = "Suite";
        public static string SMOKING = "Smoking";
        public static string NON_SMOKING = "Non-Smoking";

        /// <summary>
        /// This is the auto-generated booking number for the reservation.
        /// It is generated by the database upon saving the reservation.  (Or it should be)
        /// </summary>
        public int BookingNumber { get; set; }

        public string GuestFirstName { get; set; }

        public string GuestLastName { get; set; }

        /// <summary>
        /// This is misnamed, but I am unable to update the client project, so we are stuck with it.
        /// </summary>
        public string guestEmail { get; set; }

        public DateTime CheckInDate { get; set; }

        public DateTime CheckOutDate { get; set; }

        /// <summary>
        /// This is a calculated field.  It is the number of nights the guest will be staying.
        /// </summary>
        public int NumberOfNights => (CheckOutDate - CheckInDate).Days;

        /// <summary>
        /// The name of this field is unclear.  Is this the total number of guests, or the number of additional guests beyond the primary guest?
        /// </summary>
        public int NumberOfAdditionalGuests { get; set; }

        /// <summary>
        /// Accepted values =
        /// - Single
        /// - Double
        /// - Suite
        /// </summary>
        public string RoomType { get; set; }

        /// <summary>
        /// Accepted values =
        /// - Smoking
        /// </summary>
        public string SmokingOrNonSmoking { get; set; }

        /// <summary>
        /// This is the price per night for the reservation.  This is not a calculated field, but
        /// is determined during the ReservationService.
        /// </summary>
        internal double PricePerNight { get; set; } = 100;

        /// <summary>
        /// The total cost of the reservation.
        /// This is determined during the ReservationService and is based on the number of nights, the type of room booked and the weather.
        /// </summary>
        internal double Total { get; set; }

    }
}